#!/bin/bash
here="`pwd`"
list=""
for i in $@ ; do
  list="$list $here/$i"
done
cd "/Applications/MPlayer OSX Extended.app/Contents/Resources/Binaries/mpextended.mpBinaries/Contents/MacOS"
pwd
[ ! -z "$list" ] \
  && ./mplayer $list
